[Appearance]
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Maple Mono NF,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
cursor_flash_time=1000
double_click_interval=400

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5\x65\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5\x65\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xec\0\0\x5\x65)
