[Appearance]
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Maple Mono NF,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Noto Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
cursor_flash_time=1000
double_click_interval=400
